#!/usr/bin/env php
<?php
require "api.php";
require "settings.php";
date_default_timezone_set("America/New_York");
$api=new phpbbRemoteApi(PHPBB_URL,PHPBB_FORUM,PHPBB_TOPIC,PHPBB_USER,PHPBB_PASSWORD);
while($n=$api->get_unread_pm())
{
  $api->download_pm($n);
  $api->delete_pm($n);
}
