#!/usr/bin/env php
<?php
require "api.php";
require "settings.php";
date_default_timezone_set("America/New_York");
$api=new phpbbRemoteApi(PHPBB_URL,PHPBB_FORUM,PHPBB_TOPIC,PHPBB_USER,PHPBB_PASSWORD);
echo $api->update_num_posts()."\n";
for($i=0;$i<$api->num_posts;$i++)
{
  if(file_exists("posts/$i")) { continue; }
  $api->download_post($i);
}
