#!/usr/bin/env php
<?php
require "api.php";
require "settings.php";
date_default_timezone_set("America/New_York");
$api=new phpbbRemoteApi(PHPBB_URL,PHPBB_FORUM,PHPBB_TOPIC,PHPBB_USER,PHPBB_PASSWORD);
if(file_exists("whispers_data"))
{
  $whispers_data=unserialize(file_get_contents("whispers_data"));
}
else
{
  $whispers_data=[];
  foreach(unserialize(FMBOT_PLAYERS) as $player)
  {
    $whispers_data[$player]=FMBOT_WHISPERS_PER_PLAYER;
  }
}
$newpms=explode("\n",file_get_contents("pms/unhandled"));
$unhandled=[];
foreach($newpms as $i)
{
  if(trim($i)=="") continue;
  $pm=$api->get_pm($i);
  $player=null;
  foreach(unserialize(FMBOT_PLAYERS) as $pplayer)
  {
    if($pm->subject==="Whisper to $pplayer"||$pm->subject==="Re: Whisper to $pplayer")
    {
      $player=$pplayer;
    }
  }
  if(!$player) // Not a 'Whisper to <player> PM'
  {
    $unhandled[]=$i;
    continue;
  }
  /*if($player===$pm->author)
  {
    $api->create_pm("Re: Whisper to $player","You cannot whisper to yourself, that would be weird.",[$pm->author]);
    continue;
  }*/
  if(strlen(trim($pm->conts))>FMBOT_WHISPER_LENGTH)
  {
    $api->create_pm("Re: Whisper to $player","The maximum length for one whisper is 200 characters.  Please shorten your whisper and re-submit it.",[$pm->author]);
    continue;
  }
  $whispers_data[$pm->author]--;
  $api->create_pm("Whisper from $player","[quote=\"".$pm->author."\"]".$pm->conts."[/quote]",[$player]);
}
file_put_contents("pms/unhandled",implode("\n",$unhandled));
file_put_contents("whispers_data",serialize($whispers_data));
