<?php
define("PHPBB_URL","");
define("PHPBB_FORUM",0);
define("PHPBB_TOPIC",0);
define("PHPBB_USER","");
define("PHPBB_PASSWORD","");
define("FMBOT_PLAYERS",serialize(["a","b","c"]));
define("FMBOT_NUM_LIVE_PLAYERS",0);
define("FMBOT_JENKINS_URL","http://127.0.0.1:8080");
define("FMBOT_LOCAL",true);
